DROP TABLE IF EXISTS calendar_subscriptions;

DROP TABLE IF EXISTS events;

DROP TABLE IF EXISTS calendar;

DROP TABLE IF EXISTS license;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS person;


CREATE TABLE person (id SERIAL PRIMARY KEY, firstname VARCHAR(127), lastname VARCHAR(127), usualname VARCHAR(127));

CREATE TABLE users (id SERIAL PRIMARY KEY, login VARCHAR(127) NOT NULL UNIQUE, password VARCHAR(31) NOT NULL, status SMALLINT NOT NULL, personid BIGINT NOT NULL UNIQUE REFERENCES person);

CREATE TABLE license (id SERIAL PRIMARY KEY, userid BIGINT NOT NULL REFERENCES users, startdate TIMESTAMP, enddate TIMESTAMP);

CREATE TABLE calendar (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, ownerid BIGINT REFERENCES users);

CREATE TABLE events (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, category SMALLINT NOT NULL, owner BIGINT NOT NULL REFERENCES users, comments VARCHAR(255), tstamp TIMESTAMP, startdate TIMESTAMP NOT NULL, enddate TIMESTAMP NOT NULL, status SMALLINT NOT NULL, frequency SMALLINT NOT NULL, maxdate TIMESTAMP, overrides BIGINT REFERENCES events, calendar BIGINT NOT NULL REFERENCES calendar);

CREATE TABLE calendar_subscriptions (id SERIAL PRIMARY KEY, calendarid BIGINT NOT NULL REFERENCES calendar, userid BIGINT NOT NULL REFERENCES users, role SMALLINT NOT NULL);

